
[[main]]
  name = "Science"
  identifier = "science"
  url = "/science"
  weight = "10"

[[main]]
  name = "Sports"
  identifier = "sports"
  url = "/sports/"
  weight = "20"

[[main]]
  name = "Writing"
  identifier = "writing"
  weight = "30"

[[main]]
  name = "Blog"
  parent = "writing"
  url = "/post/"
  weight = "31"

[[main]]
  name = "Photography"
  url = "/photos/"
  identifier = "photos"
  weight = "40"

[[main]]
  name = "About"
  identifier = "about"
  weight = "50"

[[main]]
  name = "CV"
  parent = "about"
  url = "simonis_cv.pdf"
  weight = "51"

[[main]]
  name = "<i class='ai ai-google-scholar'></i>"
  parent = "about"
  url = "https://scholar.google.co.uk/citations?hl=en&user=XXg3600AAAAJ"
  weight = 52

[[main]]
  name = "<i class='fab fa-orcid'></i>"
  parent = "about"
  url = "https://orcid.org/0000-0001-9798-0460"
  weight = 53

[[main_right]]
  url = "/contact/"
  name = "<i class='far fa-envelope'></i>"
  identifier = "email"
  weight = 1

[[main_right]]
  url = "https://www.github.com/juniperlsimonis"
  name = "<i class='fab fa-github-alt'></i>"
  identifier = "github"
  weight = 2

[[main_right]]
  url = "https://www.twitter.com/juniperlsimonis"
  name = "<i class='fab fa-twitter'></i>"
  identifier = "twitter"
  weight = 3