
[[main]]
  name = "Science"
  identifier = "science"
  url = "/science"
  weight = "10"

[[main]]
  name = "Sports"
  identifier = "sports"
  url = "/sports/"
  weight = "20"

[[main]]
  name = "Writing"
  identifier = "writing"
  weight = "30"

[[main]]
  name = "Blog"
  parent = "writing"
  url = "/post/"
  weight = "31"

[[main]]
  name = "Photography"
  url = "/photos/"
  identifier = "photos"
  weight = "40"

[[main]]
  name = "Music"
  url = "/music/"
  identifier = "music"
  weight = "0"



[[main_right]]
  name = "<i class='ai ai-cv'></i>"
  identifier = "cv"
  url = "simonis_cv.pdf"
  weight = "1"

[[main_right]]
  name = "<i class='ai ai-google-scholar'></i>"
  identifier = "google"
  url = "https://scholar.google.co.uk/citations?hl=en&user=XXg3600AAAAJ"
  weight = 2

[[main_right]]
  name = "<i class='fab fa-orcid'></i>"
  identifier = "orcid"
  url = "https://orcid.org/0000-0001-9798-0460"
  weight = 3

[[main_right]]
  url = "https://www.github.com/juniperlsimonis"
  name = "<i class='fab fa-github-alt'></i>"
  identifier = "github"
  weight = 4

[[main_right]]
  url = "https://www.twitter.com/juniperlsimonis"
  name = "<i class='fab fa-twitter'></i>"
  identifier = "twitter"
  weight = 5


[[main_right]]
  url = "/contact/"
  name = "<i class='far fa-envelope'></i>"
  identifier = "email"
  weight = 6

