
theme = "jls_forest"
day_night = true
font = "native"
font_size = "L"

site_type = "Person"
description = "Homepage of Dr. Juniper L. Simonis."


highlight = true
highlight_languages = ["r"] 
highlight_style = "github"  

math = true

diagram = true

privacy_pack = true

show_related = false


email = "contact@juniperlsimonis.com"
phone = ""
address = {street = "", city = "", region = "", postcode = "", country = "", country_code = ""}
coordinates = {latitude = "", longitude = ""}
directions = ""
office_hours = ""
appointment_url = ""
contact_links = []

sharing_image = "sharing_image.jpg"

twitter = "juniperlsimonis"

date_format = "Jan 2, 2006"
time_format = "3:04 PM"

address_format = "en-us"

main_menu = {enable = true, align = "r", show_logo = true, highlight_active_link = true, show_language = false, show_day_night = true, show_search = true}

sharing = true

copyright_license = {enable = true, allow_derivatives = true, share_alike = false, allow_commercial = true}

plugins_js  = []
plugins_scss = ["custom"]

[avatar]
  gravatar = false
  shape = "circle"

[publications]
  date_format = "January 2006"
  citation_style = "apa"

[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

[comments]
  provider = ""
  commentable = {page = false, post = false, docs = false, project = false, publication = false, talk = false}

  [comments.disqus]
    shortname = ""
    show_count = true  

  [comments.commento]
    url = ""

[search]
  provider = "wowchemy"
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

[map]
  provider = "mapnik"
  api_key = ""
  zoom = 15

[marketing]
  google_analytics = ""
  google_tag_manager = ""
  google_site_verification = ""

[cms]
  branch = "main"
  local_backend = false

[icon.pack]
  ai = true  
